In [1]:
import pandas as pd
import pandas_datareader as pdr
import numpy as np
import matplotlib.pyplot as plt
import matplotlib
import statsmodels.api as sm
from statsmodels.regression.rolling import RollingOLS
matplotlib.style.use('ggplot')

In [2]:
ff5 = pdr.famafrench.FamaFrenchReader('Emerging_5_Factors',start = '2000-01-01').read()[0]

In [4]:
ff5_new = ff5.copy()
ff5_new['Mkt'] = ff5_new['Mkt-RF'] + ff5_new['RF']
#cols = ['SMB', 'HML', 'RMW', 'CMA', 'Mkt']
cols = ['SMB', 'HML', 'Mkt']

In [5]:
ff5_new[cols]

          SMB    HML    Mkt
Date
2000-01  4.17   2.93   0.83
2000-02 -0.43 -11.54   2.94
2000-03  0.49  -0.84   0.65
2000-04  0.06   3.68 -10.87
2000-05 -0.53   1.60  -2.60
...       ...    ...    ...
2020-08  1.87  -0.55   2.57
2020-09  0.50   0.25  -1.72
2020-10 -2.17  -0.46   1.67
2020-11  1.03   6.06  10.14
2020-12 -1.63   1.04   7.19

[252 rows x 3 columns]

In [8]:
ff5_new[cols].describe()

              SMB         HML         Mkt
count  252.000000  252.000000  252.000000
mean    -0.029643    0.614563    0.832976
std      1.760412    2.078684    6.068327
min     -6.950000  -11.540000  -27.230000
25%     -0.962500   -0.555000   -2.400000
50%     -0.015000    0.410000    1.090000
75%      1.100000    1.875000    4.767500
max      6.520000    6.200000   17.980000